# Usage:
#
# 1) Get OMEGACEN_CREDENTIALS from https://metis.strw.leidenuniv.nl/wiki/doku.php?id=ait:archive
# export OMEGACEN_CREDENTIALS=username:password
#
# 2) Build the image
# podman build --secret=id=OMEGACEN_CREDENTIALS,type=env -t metis_stable .
#
# 3) Run the image
# podman-compose up

FROM docker.io/library/debian:forky
# Forky has a new enough git to have --revision, but also still Python 3.12.

MAINTAINER Hugo Buddelmeijer <hugo@buddelmeijer.nl>

# Run-time dependencies:
# - postgresql: for psql to connect to the database manually
# - media-types: to have the dataserver return image/fits content-type.
#
# Build dependencies:
#
# For MTR:
# - xcb
# - libxkbcommon-dev
# - libxkbcommon-x11-dev
# - libxcb-cursor-dev
# - libxcb-keysyms1-dev
# - libxcb-icccm4-dev
# - libxcb-shape0-dev
# - python3-pyqt6
#
# Development dependencies:
# -
#
# Optional dependencies for convenience:
# - x11-apps: for xclock to test X11 connection
# - emacs: to use as EDITOR
# - file less curl vim man-db meld tmux inetutils-ping
RUN \
    apt-get update; \
    apt-get upgrade -y; \
    apt-get install -y \
        media-types \
        build-essential \
        pkg-config \
        postgresql \
        wget gcc  automake autogen libtool gsl-bin libgsl-dev \
        libfftw3-bin libfftw3-dev fftw-dev \
        curl bzip2 subversion git cppcheck lcov valgrind \
        zlib1g zlib1g-dev \
        liberfa1 liberfa-dev \
        libcurl4-openssl-dev libcurl4 \
        less man-db x11-apps apt-file inetutils-ping \
        tmux ripgrep file \
        libcfitsio-bin libcfitsio-dev \
        wcslib-dev wcslib-tools \
        perl cmake \
        graphviz meld \
        xcb libxkbcommon-dev  libxkbcommon-x11-dev libxcb-cursor-dev \
        libxcb-keysyms1-dev libxcb-icccm4-dev  libxcb-shape0-dev \
        python3-pyqt6 \
        python-is-python3 \
        python3 \
        python3-pip \
        emacs vim nano;

# TODO: Use a lock file so also the dependencies are hardcoded.
# TODO: pybind11: pycpl does not work with pybind11 3.0.3, see https://jira.eso.org/browse/PIPE-12896
# ivh.github.io is necessary for pycpl that includes cpl
# pip.entropynaut.com is necessary for metiswise, commonwise, dataserverwise, metis-drld, eso-pymetis
# ftp.eso.org is necessary for pyesorex, edps, and adaric_core
# --break-system-packages should be fine because we are not the system python
# for anything else
RUN --mount=type=secret,id=OMEGACEN_CREDENTIALS \
    pip3 install --break-system-packages \
    --extra-index-url https://ivh.github.io/pycpl/simple/ \
    --extra-index-url https://ftp.eso.org/pub/dfs/pipelines/libraries \
    --extra-index-url https://$(cat /run/secrets/OMEGACEN_CREDENTIALS)@pip.entropynaut.com/packages \
    pytest \
    jupyter \
    "pybind11==3.0.2" \
    "pycpl==1.0.3.post4" \
    "metis-drld==0.0.3" \
    "dataserverwise==2026.5.0" \
    "commonwise==2026.5.0" \
    "metiswise==0.0.3" \
    metis-simulations \
    "eso-pymetis==0.1.0" \
    "pyesorex==1.0.3" \
    "edps==1.7.1" \
    "adari_core==4.3.0"

# Create a directory where to checkout the repositories.
# This directory can then be mounted over in the development environment.
RUN mkdir -p /root/repos
WORKDIR /root/repos

# Clone all METIS projects.
# This is still necessary because not all projects have everything they need
# in the pip package.
RUN \
    git clone https://github.com/AstarVienna/ScopeSim --revision=v0.11.4 ; \
    git clone https://github.com/AstarVienna/ScopeSim_Templates --revision=v0.8.1 ; \
    git clone https://github.com/AstarVienna/ScopeSim_Data --revision=v2025.11.15 ; \
    git clone https://github.com/AstarVienna/irdb --revision=METIS.2026-04-17 ; \
    git clone https://github.com/AstarVienna/METIS_DRLD --revision=v2026.05.15 ; \
    git clone https://github.com/AstarVienna/METIS_Simulations --revision=v20260520 ; \
    git clone https://github.com/AstarVienna/METIS_Pipeline --revision=v0.4.0 ; \
    git clone https://github.com/AstarVienna/METIS_Pipeline_Test_Data --revision=v2025.08.15 ; \
    git clone https://github.com/eiseleb47/metis-meta-package --revision=ce55da71e9126428af1ae91d12b436d4880fc359 ; \
    git clone https://github.com/AstarVienna/MTR --revision=0df99963ff41078be37f89cfc772d0ae603a046a ; \
    git clone https://github.com/AstarVienna/MetisWISE --revision=main ;

# Create data directories.
# These will be mounted over by podman-compose, but having them makes it
# possible to run the image standalone.
RUN mkdir -p /root/space/control
RUN mkdir -p /root/space/EDPS_data
RUN mkdir -p /root/space/raw
RUN mkdir -p /root/space/processed

# Set MTR configuration
ENV METIS_META_PKG "/root/repos/metis-meta-package/"
# For some reason MTR expects METIS_Simulations to exist within its own directory.
RUN ln -s /root/repos/METIS_Simulations /root/repos/MTR

# Copy configuration.
RUN mkdir -p "/root/.edps"
COPY config/DOTedps/application.properties /root/.edps/
COPY config/DOTedps/logging.yaml /root/.edps/
COPY config/breakpoints.json /root/.edps/

RUN mkdir -p "/root/.awe"

COPY scripts/Environment.cfg /root/.awe/Environment.cfg

ENV AWETARGET metiswise

ENV PYESOREX_PLUGIN_DIR "/root/repos/METIS_Pipeline/metisp/pyrecipes/"
ENV PYCPL_RECIPE_DIR "/root/repos/METIS_Pipeline/metisp/pyrecipes/"

ENV DEFAULT_IRDB_LOCATION "/root/repos/irdb/"
ENV MSIM_YAML_DIR "/root/repos/METIS_Simulations/YAML/ESO"
ENV MSIM_NCORES "3"
ENV MSIM_OUTDIR "/root/space/raw/"

# TODO: Ensure that it is not necessary to set the PYTHONPATH at all
ENV PYTHONPATH "/root/repos/METIS_DRLD:/root/repos/METIS_Pipeline/metisp/pymetis/src/:/root/repos/MetisWISE"

# TODO: Replace with the large data?
ENV SOF_DATA "/root/repos/METIS_Pipeline_Test_Data/metis_sim_small_1/data"
ENV SOF_DIR "/root/repos/METIS_Pipeline_Test_Data/metis_sim_small_1/sof"

WORKDIR "/root"
