# Usage:
#
# 1) Get OMEGACEN_CREDENTIALS from https://metis.strw.leidenuniv.nl/wiki/doku.php?id=ait:archive
# export OMEGACEN_CREDENTIALS=username:password
#
# 2) Build the image
# podman build --secret=id=OMEGACEN_CREDENTIALS,type=env -t metis_stable .
#
# 3) Run the image
# podman-compose up

FROM quay.io/condaforge/miniforge3:25.3.0-3
# /opt/conda/lib/python3.12 is hardcoded in some (dbviewer) scripts, so update those if necessary.

MAINTAINER Hugo Buddelmeijer <hugo@buddelmeijer.nl>

# Run-time dependencies:
# - postgresql: for psql to connect to the database manually
# - media-types: to have the dataserver return image/fits content-type.
#
# Build dependencies:
#
# For MTR:
# - xcb
# - libxkbcommon-dev
# - libxkbcommon-x11-dev
# - libxcb-cursor-dev
# - libxcb-keysyms1-dev
# - libxcb-icccm4-dev
# - libxcb-shape0-dev
#
# Development dependencies:
# -
#
# Optional dependencies for convenience:
# - x11-apps: for xclock to test X11 connection
# - emacs: to use as EDITOR
# - file less curl vim man-db meld tmux inetutils-ping
RUN \
    apt-get update; \
    apt-get upgrade -y; \
    apt-get install -y \
        media-types \
        build-essential \
        pkg-config \
        postgresql \
        wget gcc  automake autogen libtool gsl-bin libgsl-dev libfftw3-bin libfftw3-dev fftw-dev \
        curl bzip2 subversion git cppcheck lcov valgrind \
        zlib1g zlib1g-dev \
        liberfa1 liberfa-dev \
        libcurl4-openssl-dev libcurl4 \
        less man-db x11-apps apt-file inetutils-ping \
        tmux ripgrep file \
        libcfitsio-bin libcfitsio-dev \
        wcslib-dev wcslib-tools \
        perl cmake \
        graphviz meld \
        xcb libxkbcommon-dev  libxkbcommon-x11-dev libxcb-cursor-dev \
        libxcb-keysyms1-dev libxcb-icccm4-dev  libxcb-shape0-dev \
        emacs vim nano;

# Install
# - cpl: easy from conda
# - git: newest version allows --revision
# - common: pip installation is currently broken.
# - dataserver: to have a local dataserver installation.
# - psycopg2: because it is necessary for common.
RUN --mount=type=secret,id=OMEGACEN_CREDENTIALS \
    conda config --add channels conda-forge; \
    conda config --add channels omegacen; \
    conda config --add channels "https://$(cat /run/secrets/OMEGACEN_CREDENTIALS)@conda.astro-wise.org/"; \
    conda install -y \
          "cpl==7.3.2" \
          git \
          "common==2025.11.1" \
          "dataserver==2025.11.0" \
          psycopg2;

# Setting CPLDIR is necessary to install pycpl
ENV CPLDIR=/opt/conda

# TODO: Install common also through pip. Unfortunately it currently does not
# contain the static files needed for the dbviewer.
#RUN --mount=type=secret,id=OMEGACEN_CREDENTIALS \
#    pip install \
#    --extra-index-url "https://$(cat /run/secrets/OMEGACEN_CREDENTIALS)@pip.entropynaut.com/packages/" \
#    "commonwise"

RUN pip install pytest jupyter

# TODO: Use a lock file so also the dependencies are hardcoded.
RUN pip install \
    --extra-index-url https://ftp.eso.org/pub/dfs/pipelines/libraries \
    "pycpl==1.0.3" \
    "pyesorex==1.0.3" \
    "edps==1.6.0" \
    "adari_core==4.1.0"

# Create a directory where to checkout the repositories.
# This directory can then be mounted over in the development environment.
RUN mkdir -p /root/repos
WORKDIR /root/repos


# Clone all METIS projects
# Use git clones instead of pip installs because this makes it easier
# to have the same scripts in both the Stable and the Head Containerfiles.
RUN \
    git clone https://github.com/AstarVienna/ScopeSim --revision=v0.11.1 ; \
    git clone https://github.com/AstarVienna/ScopeSim_Templates --revision=0.7.0 ; \
    git clone https://github.com/AstarVienna/ScopeSim_Data --revision=v2025.11.15 ; \
    git clone https://github.com/AstarVienna/speXtra ; \
    git clone https://github.com/AstarVienna/irdb --revision=METIS.2025-10-26 ; \
    git clone https://github.com/AstarVienna/METIS_DRLD --revision=v2025.11.15 ; \
    git clone https://github.com/AstarVienna/METIS_Simulations --revision=v2025.11.15 ; \
    git clone https://github.com/AstarVienna/METIS_Pipeline --revision=v0.2.3 ; \
    git clone https://github.com/AstarVienna/METIS_Pipeline_Test_Data --revision=v2025.02.15 ; \
    git clone https://github.com/eiseleb47/metis-meta-package ; \
    git clone https://github.com/AstarVienna/MTR ; \
    git clone https://github.com/AstarVienna/MetisWISE --revision=v2025.11.15 ;

# Install all METIS projects.
# METIS_Simulations / ScopeSim_Templates / ScopeSim should be installed in
# this order because otherwise they might install different versions of
# each other. \
RUN \
    pip install -e METIS_Simulations ; \
    pip install -e ScopeSim_Templates ; \
    pip install -e ScopeSim ; \
    pip install -e speXtra ; \
    pip install -e MetisWISE ; \
    pip install -e ScopeSim_Data ;

# Create data directories.
# These will be mounted over by podman-compose, but having them makes it
# possible to run the image standalone.
RUN mkdir -p /root/space/control
RUN mkdir -p /root/space/EDPS_data
RUN mkdir -p /root/space/raw
RUN mkdir -p /root/space/processed

# Create recipe directory that is not actually used, but otherwise
# pyesorex complains.
RUN mkdir -p /opt/conda/lib/esopipes-plugins

# Set MTR configuration
ENV METIS_META_PKG "/root/repos/metis-meta-package/"
# For some reason MTR expects METIS_Simulations to exist within its own directory.
RUN ln -s /root/repos/METIS_Simulations /root/repos/MTR


# Copy configuration.
RUN mkdir -p "/root/.edps"
COPY config/DOTedps/application.properties /root/.edps/
COPY config/DOTedps/logging.yaml /root/.edps/
COPY config/breakpoints.json /root/.edps/

RUN mkdir -p "/root/.awe"

COPY scripts/Environment.cfg /root/.awe/Environment.cfg

ENV AWETARGET metiswise

ENV PYESOREX_PLUGIN_DIR "/root/repos/METIS_Pipeline/metisp/pyrecipes/"
ENV PYCPL_RECIPE_DIR "/root/repos/METIS_Pipeline/metisp/pyrecipes/"

ENV DEFAULT_IRDB_LOCATION "/root/repos/irdb/"
ENV MSIM_YAML_DIR "/root/repos/METIS_Simulations/YAML/ESO"
ENV MSIM_NCORES "3"
ENV MSIM_OUTDIR "/root/space/raw/"

# TODO: Ensure that it is not necessary to set the PYTHONPATH at all
ENV PYTHONPATH "/root/repos/METIS_DRLD:/root/repos/METIS_Pipeline/metisp/pymetis/src/:/root/repos/MetisWISE"

# TODO: Replace with the large data?
ENV SOF_DATA "/root/repos/METIS_Pipeline_Test_Data/metis_sim_small_1/data"
ENV SOF_DIR "/root/repos/METIS_Pipeline_Test_Data/metis_sim_small_1/sof"

WORKDIR "/root"
